services:

  crawler:
    build: .
    container_name: marketbot-crawler
    ports:
      - "3333:3333"
    env_file:
      - local.env
    volumes:
      - .:/app
    networks:
      - default
      - bot-network

networks:
  default:
  bot-network:
    external: true
